### ISSUE TITLE
counter in RectProgressBar is not showing the exact data 

### ISSUE THREAD

**Issue by ashosive** [kevoese/react-animated-progress-bar#21]
Counter in RectProgressBar is on 102% even i gave **percentage="100"**
please look into this .
![image](https://user-images.githubusercontent.com/65212969/189553453-da1067c9-d9a7-4f78-8344-0c1dff74d3bb.png)

**Comment by Akshay-Arjun** [comment]
Same problem. Any solutiuion?

**Comment by kevoese** [comment]
This issue is resolved. Kindly check out the new version
