### ISSUE TITLE
Counter Not showing exact data.

### ISSUE THREAD

**Issue by Akshay-Arjun** [kevoese/react-animated-progress-bar#23]
The progress bar is working fine but the percentage inside the bar is showing wrong. It is adding +2 to every value passed.
Example 1 :
![image](https://user-images.githubusercontent.com/68991993/205498420-1925f98d-d304-40b4-a812-e1bfd23dc6d0.png)
![image](https://user-images.githubusercontent.com/68991993/205498430-20c1599c-7ea6-4157-b9ca-b1c9fa3e5279.png)
Example 2 : 
![image](https://user-images.githubusercontent.com/68991993/205498480-eb125bcb-2c44-4e2c-b04a-0d1c0bac8e23.png)
![image](https://user-images.githubusercontent.com/68991993/205498486-152e27d0-388b-4420-8bdf-9685af96ef24.png)

**Comment by kevoese** [comment]
Hello. This is resolved. Check out the new version

**Comment by Akshay-Arjun** [comment]
Thank you for the quick fix. Tested and it works.
